### ISSUE TITLE
[Bug]: No __init__.py in vacuumcontroller

### ISSUE THREAD

**Issue by amalie-trewartha** [CederGroupHub/alab_control#69]
### Version

newest

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

VacuumController doesn't install correctly due to lack of __init__.py file in the folder

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amalie-trewartha** [comment]
Same with labman/database/views

**Comment by idocx** [comment]
I have added `__init__.py` to both folders. Thank you for reporting this!
